<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Quem somos</h1>
            <p class="col-md-8 fs-4">Usando tecnologia de um jeito inimaginável, a <a class="text-decoration-none link-success " href="<?= HOME; ?>/">Invencible</a> fará um transformação de como você vê a tecnologia</p>
            <a href="<?=HOME;?>/contact" class="btn btn-primary btn-lg" >Entre em contato</a>
        </div>
    </div>

    <div class="col-md-12">
        <p>Lorem ipsum dolor sit amet consectetur totam facilis ut hic maiores assumenda aut, asperiores expedita corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod, magni aspernatur officiis totam facilis ut hic maiores assumenda aut, asperiores expedita corporis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod, magni aspernatur officiis totam facilis ut hic maiores assumenda aut, asperiores expedita corporis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod.</p>
        <p>Lorem ipsum dolor sit amet consectetur totam facilis ut hic maiores assumenda aut, asperiores expedita corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod, magni aspernatur officiis totam facilis ut hic maiores assumenda aut, asperiores expedita corporis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod, magni aspernatur officiis totam facilis ut hic maiores assumenda aut, asperiores expedita corporis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod.</p>
        <h2 class="mt-5">Mais sobre nós</h2>
        <div class="accordion accordion-flush" id="accordionFlushExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseOne" aria-expanded="false" aria-controls="flush-collapseOne">
                        Missão
                    </button>
                </h2>
                <div id="flush-collapseOne" class="accordion-collapse collapse" aria-labelledby="flush-headingOne" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Lorem Ipsum dolor sit amet is a simply dummy text...</div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingTwo">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseTwo" aria-expanded="false" aria-controls="flush-collapseTwo">
                        Visão
                    </button>
                </h2>
                <div id="flush-collapseTwo" class="accordion-collapse collapse" aria-labelledby="flush-headingTwo" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Lorem Ipsum dolor sit amet is a simply dummy text...</div>
                </div>
            </div>
            <div class="accordion-item">
                <h2 class="accordion-header" id="flush-headingThree">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#flush-collapseThree" aria-expanded="false" aria-controls="flush-collapseThree">
                        Valores
                    </button>
                </h2>
                <div id="flush-collapseThree" class="accordion-collapse collapse" aria-labelledby="flush-headingThree" data-bs-parent="#accordionFlushExample">
                    <div class="accordion-body">Lorem Ipsum dolor sit amet is a simply dummy text...</div>
                </div>
            </div>
        </div>
        <p class="mt-5">Lorem ipsum dolor sit amet consectetur totam facilis ut hic maiores assumenda aut, asperiores expedita corporis. Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod, magni aspernatur officiis totam facilis ut hic maiores assumenda aut, asperiores expedita corporis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod, magni aspernatur officiis totam facilis ut hic maiores assumenda aut, asperiores expedita corporis.Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptatem excepturi recusandae molestias possimus doloribus deleniti ipsa quod.</p>


    </div>
</div>
<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>