<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<main>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-normal">InvencibleWork</h1>
            <p class="lead fw-normal">É preciso entender que há mais de um caminho para subir a montanha</p>
            <a class="btn btn-outline-secondary" href="#">Em breve</a>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</main>

<section>
    <div class="container d-flex">
        <div class="col-md-12" d-flex>
            <?php foreach ($this->products as $product) : ?>
                <div class="col-md-4  d-flex">
                    <div class="card " style="width: 18rem;">
                        <img src="http://via.placeholder.com/640x360?text=<?= $product['name']; ?>" class="card-img-top" alt="...">
                        <div class="card-body">
                            <h5 class="card-title"><?= $product['name']; ?></h5>
                            <p class="card-text"><?= $product['description']; ?></p>
                            <a href="<?= HOME; ?>/product/<?= $product['id']; ?>" class="btn btn-primary">Comprar</a>
                        </div>
                    </div>
                </div>
                <?php endforeach; ?>

        </div>
    </div>
</section>



<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>