<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <h1>Fazer login</h1>
        <hr>
    </div>
    <div class="d-flex justify-content-center cols-12">

        
        <form method="POST" action="<?= HOME; ?>/auth/login">
            <div class="teste">
                
                <div class="col-md-12">
                    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
                </div>

                <div class="mb-2 form-group col-12" id="form">
                    <label for="email" class="form-label">E-mail</label>
                    <input type="email" name="email" class="form-control" id="email" placeholder="Insira seu e-mail">
                </div>

                <div class="mb-2 form-group" id="form">
                    <label for="password" class="form-label">Senha</label>
                    <input type="password" name="password" class="form-control" id="password" placeholder="***************************">
                </div>

                <button type="submit" class="btn btn-primary btn-lg mt-2">Entrar</button>

            </div>


        </form>
    </div>
</div>

<style>
    /* .teste {
        background-color: red;
    } */
</style>


<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>