<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<main>
    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>



    <div class="col-md-12">
        <div class="nav">
            <?php foreach ($this->categories as $category) : ?>

                <a style="margin-right:7px ;" class="badge rounded-pill text-bg-primary mr-2" href="<?= HOME . '/category/' . $category['slug'] ?>"><?= $category['name'] ?></a>

            <?php endforeach; ?>
        </div>



    </div>

    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-normal">MyPosts</h1>
            <p class="lead fw-normal">Crie tópicos sobre qualquer assunto e resolva o seu problema com MyPosts</p>
            <a class="btn btn-outline-secondary" href="#">Em breve</a>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</main>

<section>
    <div class="container">
        <div class="col-md-12 d-flex justify-content-between">
            <?php foreach ($this->posts as $post) : ?>
                <div class="card" style="width: 18rem;margin-right:20px;">
                    <img src="https://via.placeholder.com/30x30" class="card-img-top" alt="...">
                    <div class="card-body">
                        <small class="text-center">
                            Criado em <?= date('d/M/Y H:i:s', strtotime($post['created_at'])); ?>
                        </small>
                        <h5 class="card-title"><?= $post['title'] ?> </h5>
                        <p class="card-text"> <?= $post['description'] ?> </p>
                        <a href="<?= HOME . '/post/' . $post['slug'] ?>" class="btn btn-primary">Ver mais</a>
                    </div>
                </div>
            <?php endforeach; ?>

        </div>
    </div>
</section>



<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>