<?php

use Code\Entity\Product;

require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <div class="col-md-7 pull-left">
            <div class="row">
                <h2>
                    <p><?= $this->post['title']; ?></p>
                </h2>
                <small class="">
                    Criado em <?= date('d/M/Y H:i:s', strtotime($this->post['created_at'])); ?>
                </small>
                <hr>
                <p><?= $this->post['description']; ?></p>
            </div>
        </div>
        <!-- <div class="col-md-4 pull-right">
            
            <div class="row">
                <h3>Sidebar</h3>
                <hr>
            </div>

            <div class="row content">
                <p>
                    lorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum dolor sit amet, consectetur adipisicing elitlorem ipsum.
                </p>
            </div>
        </div> -->
    </div>
</div>
</div>


<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>