<?php require VIEWS_PATH . 'admin/includes/header.phtml'; ?>
<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
            <h1 class="display-5 fw-bold">Página não encontrada!</h1>

            <a href="<?= HOME; ?>/home" class="btn btn-primary btn-lg">Voltar para Home</a>
        </div>
    </div>
</div>



<?php require VIEWS_PATH . 'admin/includes/footer.phtml'; ?>