<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <h1>MyPosts - <small>Editar Categoria</small></h1>
        <hr>
    </div>
    <div class="col-md-12">
        <form method="POST" action="<?= HOME; ?>/categories/edit/<?= $this->category['id'] ?>">

            <div class="col-md-12">
                <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
            </div>

            <div class="mb-2 form-group" id="form">
                <label for="first_name" class="form-label">Nome</label>
                <input type="text" name="name" class="form-control" value="<?= $this->category['name'] ?>">
            </div>

            <div class="mb-2 form-group" id="form">
                <label for="description" class="form-label">Descrição</label>
                <textarea name="description" class="form-control" cols="12" rows="3"><?= $this->category['description'] ?></textarea>
            </div>
            <button type="submit" class="btn btn-primary btn-lg mt-2">Salvar</button>
        </form>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>