<?php require VIEWS_PATH . 'admin/includes/header.phtml'; ?>
<main>
    <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>



    <div class="col-md-12">

    </div>

    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-normal">AdminLoja</h1>
            <p class="lead fw-normal">Uma loja virtual com uma variedade de produtos incríveis.</p>
            <a class="btn btn-outline-secondary" href="#">Em breve</a>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</main>

<!-- <section> -->
<div class="container">
    <div class="row" style="margin-bottom: 20px;">
        <?php foreach ($this->products as $key => $product) : ?>
            <div class="col-md-4">
                <div class="card mt-2" style="width: 18rem;">
                    <img src="https://placeimg.com/640/280/any" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title"><?= $product['name'] ?></h5>
                        <p class="card-text"><?= $product['description'] ?></p>
                        <h4>R$ <?= number_format($product['price'], 2, ',', '.') ?></h4>
                        <a href="<?= HOME; ?>/product/view/<?= $product['slug'] ?>" class="btn btn-primary">Ver mais</a>
                    </div>
                </div>

            </div>
            <?php if (($key + 1) % 3 == 0) : ?> <div>
                    <div class="row" style="margin-bottom: 20px;">
            <?php endif; ?>
            <?php endforeach; ?>
                    </div>

                </div>
                <!-- </section> -->



                <?php require VIEWS_PATH . 'admin/includes/footer.phtml'; ?>