<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <link rel="icon" type="image/x-icon" href="../../favicon.ico">
    <title>Página Inicial do Painel</title>
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <a class="navbar-brand" href="<?= HOME; ?>/">AdminLoja</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
                <ul class="navbar-nav">
                    <?php if (\Code\Session\Session::has('user')) : ?>
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="<?= HOME; ?>/admin/products">Produtos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="<?= HOME; ?>/admin/users">Usuários</a>
                        </li>


                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="<?= HOME; ?>/admin/categories">Categorias</a>
                        </li>

                        <a href="<?= HOME; ?>/auth/logout" aria-current="page" class="nav-link ">Sair</a>

                    <?php else : ?>
                        <li>
                            <a href="<?= HOME; ?>/" aria-current="page" class="nav-link ">Ir Para Home</a>
                        </li>

                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
</body>

</html>