<?php require VIEWS_PATH . 'admin/includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12 mt-4">
        <h1>AdminLoja - <small>Todos os Produtos</small>
            <a href="<?= HOME; ?>/admin/products/new" class="btn btn-primary" style="margin-left: 360px;">Criar Novo Produto</a>
        </h1>
        <hr>
    </div>

    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Preço</th>
                    <th>Status</th>
                    <th>Criado em</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->products as $product) : ?>

                    <tr>
                        <td><?= $product['id']; ?></td>
                        <td><?= $product['name']; ?></td>
                        <td>
                            <?php if ($product['is_active']) : ?>
                                <span class="badge bg-success rounded">Ativo</span>
                            <?php else : ?>
                                <span class="badge bg-danger rounded">Inativo</span>
                            <?php endif; ?>
                        </td>
                        <td><?= number_format($product['price'], 2, ',', '.'); ?></td>
                        <td><?= date('d/m/Y H:i:s', strtotime($product['created_at'])); ?></td>
                        <td>
                            <a href="<?= HOME ?>/admin/products/edit/<?= $product['id']; ?>" class="btn btn-primary">Editar</a>

                            <a href="<?= HOME ?>/admin/products/remove/<?= $product['id']; ?>" class="btn btn-danger">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require VIEWS_PATH . 'admin/includes/footer.phtml'; ?>