<?php require VIEWS_PATH . 'admin/includes/header.phtml'; ?>

<div class="container">
    <!-- <div class="col-md-12 mt-4">
        <h1>AdminLoja - <small>Criar Novo Produto</small></h1>
        <hr>
    </div> -->
    <div class="row mt-3">
        <div class="col-md-12">
            <h2>Criar Novo Produto</h2>
            <hr>
        </div>
    </div>
    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>

    <div class="row">
        <form action="<?= HOME; ?>/admin/products/new" method="POST" enctype="multipart/form-data">
            <div class="col-md-12">
                <div class="form-group">
                    <label for="name">Nome do Produto</label>
                    <input type="text" name="name" class="form-control">
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label for="description">Descrição</label>
                    <input type="text" name="description" class="form-control">
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label for="content">Conteúdo</label>
                    <textarea name="content" rows="3" class="form-control"></textarea>
                </div>
            </div>

            <div class="col-md-12">

                <div class="row">
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="price">Preço</label>
                            <input type="text" name="price" class="form-control">
                        </div>
                    </div>

                    <div class="col-md-6">
                        <label for="is_active">Status do Produto</label>
                        <select name="is_active" class="form-control">
                            <option value="">Selecione o Status</option>
                            <option value="1">Ativo</option>
                            <option value="0">Inativo</option>
                        </select>
                    </div>
                </div>
            </div>


            <div class="col-md-12">
                <div class="form-group">
                    <label for="categories">Selecione as Categorias</label>
                    <select name="categories[]" multiple class="form-control">
                        <?php foreach ($this->categories as $category) : ?>
                            <option value="<?= $category['id']; ?>"><?= $category['name']; ?></option>
                        <?php endforeach; ?>

                    </select>
                </div>
            </div>

            <div class="col-md-12">
                <div class="form-group">
                    <label for="images">Foto do Produto</label>
                    <input type="file" name="images[]" multiple class="form-control">
                </div>
            </div>

            <div class="col-md-12 mt-3">
                <button type="submit" class="btn btn-primary btn-lg">Criar Produto</button>
            </div>
        </form>
    </div>
    <!--fechamento row inputs-->

</div>

<?php require VIEWS_PATH . 'admin/includes/footer.phtml'; ?>