<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12">
        <h1>MyPosts - <small>Todos os Usuários</small>
            <a href="<?= HOME; ?>/users/new" class="btn btn-primary" style="margin-left: 450px;">Criar Novo Usuário </a>
        </h1>
        <hr>
    </div>

    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Criado em</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->users as $user) : ?>

                    <tr>
                        <td><?= $user['id']; ?></td>
                        <td><?= $user['first_name'] . ' ' . $user['last_name']; ?></td>
                        <td><?= date('d/m/Y H:i:s', strtotime($user['created_at'])); ?></td>
                        <td>
                            <a href="<?= HOME ?>/users/edit/<?= $user['id']; ?>" class="btn btn-primary">Editar</a>

                            <a href="<?= HOME ?>/users/remove/<?= $user['id']; ?>" class="btn btn-danger">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>