<?php require VIEWS_PATH . 'includes/header.phtml'; ?>
<main>
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light">
        <div class="col-md-5 p-lg-5 mx-auto my-5">
            <h1 class="display-4 fw-normal">Gerenciador de Gastos Pessoais</h1>
            <p class="lead fw-normal">Organize sua vida financeira de maneira rápida, prática e segura!</p>
            <a class="btn btn-outline-secondary" href="#">Em breve</a>
        </div>
        <div class="product-device shadow-sm d-none d-md-block"></div>
        <div class="product-device product-device-2 shadow-sm d-none d-md-block"></div>
    </div>
</main>

<section>
    <div class="container d-flex">
        <div class="col-md-12" d-flex>

        </div>
    </div>
</section>



<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>