<div class="container mt-5">
    <footer class="py-3 my-4">
        <ul class="nav justify-content-center border-bottom pb-3 mb-3">
            <li class="nav-item"><a href="<?=HOME;?>/" class="nav-link px-2 text-muted">Home</a></li>
            <li class="nav-item"><a href="<?=HOME;?>/about" class="nav-link px-2 text-muted">Quem Somos</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Time</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">FAQs</a></li>
            <li class="nav-item"><a href="<?=HOME;?>/contact" class="nav-link px-2 text-muted">Contato</a></li>
        </ul>
        <p class="text-center text-muted">InvencibleWork, Inc &copy; All rights reserveds <?= date(format:'Y');?></p>
    </footer>
</div>


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
