<?php require VIEWS_PATH . 'admin/includes/header.phtml'; ?>

<div class="container">
    <div class="col-md-12 mt-4">
        <h1>AdminLoja - <small>Todas as Categorias</small>
            <a href="<?= HOME; ?>/admin/categories/new" class="btn btn-primary" style="margin-left: 360px;">Criar Nova Categoria</a>
        </h1>
        <hr>
    </div>

    <div class="col-md-12">
        <?php require VIEWS_PATH . 'includes/messages.phtml'; ?>
    </div>

    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nome</th>
                    <th>Criado em</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <?php foreach ($this->categories as $category) : ?>

                    <tr>
                        <td><?= $category['id']; ?></td>
                        <td><?= $category['name']; ?></td>
                        <td><?= date('d/m/Y H:i:s', strtotime($category['created_at'])); ?></td>
                        <td>
                            <a href="<?= HOME ?>/admin/categories/edit/<?= $category['id']; ?>" class="btn btn-primary">Editar</a>

                            <a href="<?= HOME ?>/admin/categories/remove/<?= $category['id']; ?>" class="btn btn-danger">Excluir</a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
</div>

<?php require VIEWS_PATH . 'admin/includes/footer.phtml'; ?>