<?php require VIEWS_PATH . 'includes/header.phtml'; ?>

    <div class="container">
        <div class="col-md-12">
            <h1>Cadastrar nova despesa</h1>
            <hr>
        </div>
        <div class="col-md-12">
            <form method="POST" action="<?=HOME;?>/myexpenses/new">
                <div class="mb-2 form-group" id="form">
                    <label for="exampleInputEmail1" class="form-label">Valor</label>
                    <input type="text" name="value" class="form-control" id="exampleInputEmail1" placeholder="Valor Gasto">
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label">Categoria</label> 
                    <select name="categories_id" class="form-select">
                        <option>Selectione uma categoria</option>
                        <?php foreach ($this->categories as $c): ?>
                        <option value="<?=$c['id']?>"><?=$c['name']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label">Usuários</label>
                    <select name="users_id" class="form-select">
                        <option>Selectione um usuário</option>
                        <?php foreach ($this->users as $u): ?>
                        <option value="<?=$u['id']?>"><?=$u['name']?></option>
                        <?php endforeach; ?>
                    </select>
                </div>

                <div class="form-group">
                    <label for="exampleInputPassword1" class="form-label">Descrição</label>
                    <textarea name="description" id="" cols="30" rows="5" class="form-control" ></textarea>
                </div>

                <button type="submit" class="btn btn-primary btn-lg mt-2">Salvar</button>
            </form>            
        </div>
    </div>

<?php require VIEWS_PATH . 'includes/footer.phtml'; ?>