<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>MyPosts - Suas discussões favoritas</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>

<header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap">
            <use xlink:href="#bootstrap" />
        </svg>
    </a>

    <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0 text-center">
        <li>
            <a href="<?= HOME; ?>/" class="nav-link px-2 link-secondary">Home</a>
        </li>
        <?php if (\Code\Session\Session::has('user')) : ?>

            <li>
                <a href="<?= HOME; ?>/posts" class="nav-link px-2 link-dark">Meus Posts</a>
            </li>

            <li>
                <a href="<?= HOME; ?>/users" class="nav-link px-2 link-dark">Usuários</a>
            </li>

            <li>
                <a href="<?= HOME; ?>/categories" class="nav-link px-2 link-dark">Categorias</a>
            </li>
    </ul>

    <div class="col-md-3 text-end d-flex justify-content-end" style="display:hidden ;">
        <?php $user = \Code\Session\Session::get('user'); ?>

        <!-- <h5 style="margin-right: 10px;"><?= $user['first_name'] . ' ' . $user['last_name']; ?> </h5> -->
        <h5 style="margin-right: 10px;"><?= $user['username']; ?> </h5>
        <a href="<?= HOME; ?>/auth/logout" class="btn btn-outline-primary me-2 btn-sm">Sair</a>
    <?php endif; ?>
    <a href="<?= HOME; ?>/auth/login" class="btn btn-outline-primary me-2 <?php if (\Code\Session\Session::has('user')) : ?> d-none<?php endif; ?>">Login</a>
    </div>
</header>

<body>